/**
 * BC.Problems
 * Microservice to manage problems
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProblemAddressModel } from './problemAddressModel';
import { ProblemBicycleModel } from './problemBicycleModel';
import { ProblemPartModel } from './problemPartModel';

export interface ProblemForReadModel { 
    id?: string;
    bicycle?: ProblemBicycleModel;
    userId?: string;
    userEmail?: string;
    address?: ProblemAddressModel;
    dateCreated?: Date;
    dateFinished?: Date;
    stage?: string;
    description?: string;
    parts?: Array<ProblemPartModel>;
}