/**
 * BC.Problems
 * Microservice to manage problems
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProblemAddressModel } from './problemAddressModel';
import { ProblemBicycleModel } from './problemBicycleModel';
import { ProblemPartModelModel } from './problemPartModelModel';

export interface ProblemForCreateModel {
    bicycle?: ProblemBicycleModel;
    userId?: string;
    userEmail?: string;
    address?: ProblemAddressModel;
    description?: string;
    partModels?: Array<ProblemPartModelModel>;
}
