/**
 * BC.Problems
 * Microservice to manage problems
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProblemBicycleModel { 
    id?: string;
    model?: string;
    serialNumber?: string;
}