/**
 * BC.Bicycles
 * Microservice to manage bicycles
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpStatusCode } from './httpStatusCode';

export interface AddedResponse { 
    statusCode?: HttpStatusCode;
    message?: string;
    id?: string;
}