/**
 * BicycleCompany Delivery Orders API
 * A simple ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DeliveryOrderStage = 'New' | 'InProgress' | 'OnTheWay' | 'Cancelled' | 'Finished';

export const DeliveryOrderStage = {
    New: 'New' as DeliveryOrderStage,
    InProgress: 'InProgress' as DeliveryOrderStage,
    OnTheWay: 'OnTheWay' as DeliveryOrderStage,
    Cancelled: 'Cancelled' as DeliveryOrderStage,
    Finished: 'Finished' as DeliveryOrderStage
};