/**
 * BicycleCompany Delivery Orders API
 * A simple ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type OperationType = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const OperationType = {
    NUMBER_0: 0 as OperationType,
    NUMBER_1: 1 as OperationType,
    NUMBER_2: 2 as OperationType,
    NUMBER_3: 3 as OperationType,
    NUMBER_4: 4 as OperationType,
    NUMBER_5: 5 as OperationType,
    NUMBER_6: 6 as OperationType
};